### ISSUE TITLE
wrong convert

### ISSUE THREAD

**Issue by maherkhalil07** [sodrooome/hijriah-converter#1]
if hijri date is before 1342, it will give the  Gregorian date to today date.

any update for this problem

**Comment by sodrooome** [comment]
Yes, i'm fully aware of that and that's why i'm given restriction for minimum to set hijri date only in 1343. In the spare time, i'll try to fix the method first. Thanks for pointing out!

**Comment by maherkhalil07** [comment]
Thank you
